config/routes.rb
Rails.application.routes.draw do
  resources :contacts, only: [:index, :create, :show]
  resources :selected_amenities
  resources :amenities
  resources :spaces
  resources :payments, only: [:index, :create, :show]
  resources :messages, only: [:index, :show, :create]
  resources :clients, only: [:create, :show , :index]
  post "/login", to: "sessions#create"
  # get "/get_client", to: "clients#get_client"
  get "/me", to: "clients#show"
  delete "/logout", to: "sessions#destroy"

  post "/payment", to: "charges#create"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :reviews
  resources :reservations
  resources :properties
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/amenity.rb
class Amenity < ApplicationRecord
    belongs_to :space
    has_many :selected_amenities

    validates :space_id, presence: true;
    validates :item_name, presence: true
    validates :price, presence: true;
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
    #relationships 
    has_many :properties
    has_many :spaces, through: :properties 
    has_many :messages 
    has_many :reservations 
    has_secure_password
    #validations 
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true, uniqueness: true 
    validates :phone_number, presence: true, length: {minimum: 10}
    validates :password, presence: true, length: {minimum: 4}
    validates :password_confirmation, presence: true, length: {minimum: 4}
end

app/models/contact.rb
class Contact < ApplicationRecord
    # belongs_to :client
end

app/models/message.rb
class Message < ApplicationRecord
    #relationships 
    belongs_to :client
    #validations 
    validates :client_id, presence: true 
    validates :message, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :reservation
    #validations 
    validates :reservation_id, presence: true 
    validates :payment_method, presence: true
    validates :total, presence: true 
    validates :status, presence: true, inclusion: {in: %w(paid unpaid), message: "invalid payment status"}
end

app/models/property.rb
class Property < ApplicationRecord
    belongs_to :client
    has_many :spaces
    has_many :reservations, through: :spaces

    validates :property_name, presence: true
    validates :location, presence: true
    validates :image_url, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    belongs_to :space
    # belongs_to :property
    has_many :selected_amenities
    belongs_to :client
    has_one :payment

    validates :kickoff_date, presence: true
    validates :end_date, presence: true
    validates :total_cash, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :space
    belongs_to :property
    belongs_to :client

    validates :ratings, length: {in: 1..5}
    validates :review, length: {maximum: 250}
end

app/models/selected_amenity.rb
class SelectedAmenity < ApplicationRecord
    belongs_to :amenity
    belongs_to :reservation

    validates :reservation_id, presence: true;
    validates :amenity_id, presence: true
    validates :quality, presence: true;
    validates :description, presence: true;

end

app/models/space.rb
class Space < ApplicationRecord
    belongs_to :client
    belongs_to :property
    has_many :reservations
    has_many :reviews
    has_many :amenities

    validates :property_id, presence: true;
    validates :room_size, presence: true
    validates :image_1, presence: true;
    validates :image_2, presence: true;
    validates :image_3, presence: true;
    validates :description, presence: true;
    validates :price_per_hour, presence: true;
    validates :status, presence: true;
    validates :space_category,presence: true;


    # to be changed latter
    # validates :space_category, inclusion: {in:["big", "small"]} 

end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  rescue_from ActiveRecord::RecordInvalid, with: :render_unprocessable_entity_response
  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found_response


  def index
      res = Space.all
      render json: res;
  end
  

  def create
      res = Space.create!(spaces_params)
      render json: res, status: :created
  end

  def destroy
      res = find
      res.destroy
      render json: {}
      # head :no_content
  end

  def update
      res = find
      res.update(spaces_params)
      render json: res
  end

  def show
      res = Space.find_by(property_id: params[:id])
      render json: res
  end

  private

  def find
      Space.find(params[:id])
  end

  def spaces_params
      params.permit(:property_id, :room_size, :image_1, :image_2, :image_3, :description, :price_per_hour, :status, :space_category, :client_id)
  end

  def render_unprocessable_entity_response(invalid)
      render json: { errors: invalid.record.errors.full_messages }, status: :unprocessable_entity
  end

  def render_not_found_response
      render json: { error: "Record not found" }, status: :not_found
  end
end

app/helpers/amenities_helper.rb
module AmenitiesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/spaces_helper.rb
module SpacesHelper
end

app/views/spaces/_form.html.erb
<%= form_with(model: space) do |form| %>
  <% if space.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(space.errors.count, "error") %> prohibited this space from being saved:</h2>

      <ul>
        <% space.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :client_id, style: "display: block" %>
    <%= form.number_field :client_id %>
  </div>

  <div>
    <%= form.label :room_size, style: "display: block" %>
    <%= form.text_field :room_size %>
  </div>

  <div>
    <%= form.label :image_1, style: "display: block" %>
    <%= form.text_field :image_1 %>
  </div>

  <div>
    <%= form.label :image_2, style: "display: block" %>
    <%= form.text_field :image_2 %>
  </div>

  <div>
    <%= form.label :image_3, style: "display: block" %>
    <%= form.text_field :image_3 %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :price_per_hour, style: "display: block" %>
    <%= form.number_field :price_per_hour %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <div>
    <%= form.label :space_category, style: "display: block" %>
    <%= form.text_field :space_category %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/spaces/_space.html.erb
<div id="<%= dom_id space %>">
  <p>
    <strong>Client:</strong>
    <%= space.client_id %>
  </p>

  <p>
    <strong>Room size:</strong>
    <%= space.room_size %>
  </p>

  <p>
    <strong>Image 1:</strong>
    <%= space.image_1 %>
  </p>

  <p>
    <strong>Image 2:</strong>
    <%= space.image_2 %>
  </p>

  <p>
    <strong>Image 3:</strong>
    <%= space.image_3 %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= space.description %>
  </p>

  <p>
    <strong>Price per hour:</strong>
    <%= space.price_per_hour %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= space.status %>
  </p>

  <p>
    <strong>Space category:</strong>
    <%= space.space_category %>
  </p>

</div>

app/views/spaces/edit.html.erb
<h1>Editing space</h1>

<%= render "form", space: @space %>

<br>

<div>
  <%= link_to "Show this space", @space %> |
  <%= link_to "Back to spaces", spaces_path %>
</div>

app/views/spaces/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Spaces</h1>

<div id="spaces">
  <% @spaces.each do |space| %>
    <%= render space %>
    <p>
      <%= link_to "Show this space", space %>
    </p>
  <% end %>
</div>

<%= link_to "New space", new_space_path %>

app/views/spaces/new.html.erb
<h1>New space</h1>

<%= render "form", space: @space %>

<br>

<div>
  <%= link_to "Back to spaces", spaces_path %>
</div>

app/views/spaces/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @space %>

<div>
  <%= link_to "Edit this space", edit_space_path(@space) %> |
  <%= link_to "Back to spaces", spaces_path %>

  <%= button_to "Destroy this space", @space, method: :delete %>
</div>